export default {
  foto: [
    {
      id: 'u9n30hmsbo6',
      path: '/cms/people/2973/pages/admissions_photo',
      name: '5C4310F7-4E07-436A-9CB2-B4359E3547B3.jpeg',
      size: 1467939,
      mimetype: 'image/jpeg',
      timestamp: 1661636644,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_photo/5C4310F7-4E07-436A-9CB2-B4359E3547B3.jpeg',
      preview: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_photo/5C4310F7-4E07-436A-9CB2-B4359E3547B3.jpeg.preview.jpg',
      thumbnail: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_photo/5C4310F7-4E07-436A-9CB2-B4359E3547B3.jpeg.thumbnail.jpg',
    },
  ],
  text: '01/09/2022',
  canteenDiaeten: [
    'vegetarian',
    'no_fish',
    'no_allergies',
  ],
  gsEinverstaendnisInformatikCharta: true,
  datenschutzIntranet: true,
  datenschutzSchulbroschuren: true,
  datenschutzPresseartikel: true,
  datenschutzKommunikationssupporte: true,
  notfallbogenChronischeKrankheitenNein: 'none',
  notfallbogenUpload: [
    {
      id: 'ua6rvtyx4e5',
      path: '/cms/people/2973/pages/admissions_notfallbogen',
      name: 'Notfallbogen Lorenzo.pdf',
      size: 284555,
      mimetype: 'application/pdf',
      timestamp: 1661755707,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_notfallbogen/Notfallbogen+Lorenzo.pdf',
      preview: null,
      thumbnail: null,
    },
  ],
  textstartdatum: '01/09/2022',
  nachmittagsbetreuungFreistellung: [
    'fri',
    'tue',
  ],
  dokumenteGeburtsurkunde: [
    {
      id: 'uaqg6a18t1d',
      path: '/cms/people/2973/pages/admissions_uploads',
      name: 'wird nachgereicht.pdf',
      size: 7626,
      mimetype: 'application/pdf',
      timestamp: 1661874673,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_uploads/wird+nachgereicht.pdf',
      preview: null,
      thumbnail: null,
    },
  ],
  dokumentePersonalausweis: [
    {
      id: 'uaqh593lvbz',
      path: '/cms/people/2973/pages/admissions_uploads',
      name: 'Ausweis Lorenzo.jpg',
      size: 4281247,
      mimetype: 'image/jpeg',
      timestamp: 1661874836,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_uploads/Ausweis+Lorenzo.jpg',
      preview: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_uploads/Ausweis+Lorenzo.jpg.preview.jpg',
      thumbnail: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_uploads/Ausweis+Lorenzo.jpg.thumbnail.jpg',
    },
  ],
  dokumenteAttest: [
    {
      id: 'ul3gs3gfe13',
      path: '/cms/people/2973/pages/admissions_uploads',
      name: 'Certif Lorenzo (2).pdf',
      size: 88338,
      mimetype: 'application/pdf',
      timestamp: 1664130163,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_uploads/Certif+Lorenzo+%282%29.pdf',
      preview: null,
      thumbnail: null,
    },
  ],
  schulvereinMitgliedschaft: 'yes',
  select: 'nein',
  gebuehrenUpload: [
    {
      id: 'uaqlk65h3hw',
      path: '/cms/people/2973/pages/admissions_fee',
      name: 'zahlungsnachweis.jpg',
      size: 6028239,
      mimetype: 'image/jpeg',
      timestamp: 1661875577,
      url: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_fee/zahlungsnachweis.jpg',
      preview: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_fee/zahlungsnachweis.jpg.preview.jpg',
      thumbnail: 'https://s3-eu-west-1.amazonaws.com/phidias-es-api-1/dstoulouse/cms/people/2973/pages/admissions_fee/zahlungsnachweis.jpg.thumbnail.jpg',
    },
  ],
  id: 'u9n2gt2q9d6',
  table: 'proceso:15',
  key1: '2973',
  key2: null,
  key3: null,
  author: '2971',
  dateCreated: '1661636552',
  dateModified: '1664130164',
  dateLocked: null,
  objAuthor: {
    id: '2971',
    firstName: 'Pietro',
    lastName: 'CATALANO',
    avatar: 'https://phidias-es-storage-1.s3.amazonaws.com/default_person.png',
  },
  objPerson: {
    id: '2973',
    firstName: 'Lorenzo Gaetano Daniel',
    lastName: 'CATALANO',
    avatar: 'https://phidias-es-storage-1.s3.amazonaws.com/dstoulouse/pictures/current/picture_ca52c5ffa4fb717fb06acf9d537fb478.jpg',
    objEnrollment: {
      person: '2973',
      section: '430',
      date: '1661378400',
      status: '2',
      outcome: null,
      observations: 'inscription',
      first: '1',
      modality: null,
      objSection: {
        id: '430',
        course: '223',
        name: 'Klasse 1b',
        teacher: '2195',
        representant: null,
        year: '15',
        capacity: '0',
        description: '1b',
        objCourse: {
          id: '223',
          name: 'Stufe 1',
          name_en: '15',
          category: '62',
          iorder: '0',
          report_template: null,
          sequence: '2',
          official_name: '1',
          type_restriction: '0',
          age_limit_restriction: '0',
          start_date_restriction: '1643238000',
          end_date_restriction: '1643238000',
        },
      },
    },
  },
}